name: Flask CI/CD Pipeline

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/flaskapp:${{ github.sha }} .
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/flaskapp:${{ github.sha }}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to AWS EC2
        run: |
          echo "${{ secrets.KEY_PEM }}" > key.pem
          chmod 400 key.pem
          scp -i key.pem docker-compose.yml ec2-user@${{ secrets.EC2_IP_ADDRESS }}:~
          ssh -i key.pem ec2-user@${{ secrets.EC2_IP_ADDRESS }} "docker-compose up -d"
        env:
          KEY_PEM: ${{ secrets.KEY_PEM }}
          EC2_IP_ADDRESS: ${{ secrets.EC2_IP_ADDRESS }}
